### ISSUE TITLE
This is not issue, but a request

### ISSUE THREAD

**Issue by junwhuan** [jaanonim/obsidian-youversion-linker#14]
I like the plugin very much. In YouVersion, there are many "Plans", are you able to refer the plan as well? Is it possible to do it? Maybe just a link to the plan (not the plan details). Thanks!

**Comment by jaanonim** [comment]
I'm glad you like this plugin. Thank you for your suggestion, but the purpose of this plugin is to make using the Bible easier and quicker. I chose YouVersion Bilbe because it had many translations and I just use it. There are no official APIs for YouVerison, so this would be difficult to do and is beyond the purpose of this plugin. In short: it will not be implemented.

**Comment by jaanonim** [comment]
Will resolve under #28
